default:
  tags:
    - a4s-runner
  image: docker:24.0.5
  before_script:
    - docker info

stages:
  - test
  - build

test:
  stage: test
  script:
    - docker build --target=test -t $CI_REGISTRY_IMAGE:test .
    - docker run --rm $CI_REGISTRY_IMAGE:test
  allow_failure: false

build:
  stage: build
  image: docker:cli
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "main"
  #   - if: $CI_PIPELINE_SOURCE == "web"
  #   - when: never
