version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(levelname)s: %(message)s'
  detailed:
    format: '[%(levelname)-8s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
  json:
    (): a4s_eval.utils.logging.JSONFormatter
    fmt_keys:
      level: levelname
      message: message
      timestamp: timestamp
      logger: name
      module: module
      function: funcName
      line: lineno
      thread_name: threadName
handlers:
  stdout:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout
  queue_handler:
    class: logging.handlers.QueueHandler
    handlers:
    - stdout
    respect_handler_level: true
loggers:
  root:
    level: DEBUG
    handlers:
    - queue_handler
