name: A4S-eval pipeline for github ported from gitlab

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, master]

env:
  UV_VERSION: "0.5"
  PYTHON_VERSION: "3.12"
  BASE_LAYER: "bookworm-slim"
  UV_LINK_MODE: "copy"
  UV_CACHE_DIR: ".uv-cache"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  checks:
    name: Linting and formatting stage
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:${{ env.UV_VERSION }}-python${{ env.PYTHON_VERSION }}-${{env.BASE_LAYER}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Install dependencies
        run: uv sync

      - name: Do the linting
        run: uv run ruff check .

      - name: Do the format check
        run: uv run ruff format --check .

      - name: Prune package cache
        run: uv cache prune --ci