name: A4S-eval pipeline for github ported from gitlab

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, master]

env:
  UV_VERSION: ${{ vars.A4S_EVAL_UV_VERSION }}
  PYTHON_VERSION: ${{ vars.A4S_EVAL_PYTHON_VERSION }}
  BASE_LAYER: ${{ vars.A4S_EVAL_BASE_LAYER }}
  UV_LINK_MODE: "copy"
  UV_CACHE_DIR: ".uv-cache"
  UV_PYTHON: ${{ vars.A4S_EVAL_UV_PYTHON }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  checks:
    name: Linting and formatting stage
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:${{ vars.A4S_EVAL_UV_VERSION }}-python${{ vars.A4S_EVAL_PYTHON_VERSION }}-${{ vars.A4S_EVAL_BASE_LAYER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: uv sync
      - name: Do the linting
        run: uv run ruff check .
      - name: Do the format check
        run: uv run ruff format --check .
      - name: Prune package cache
        run: uv cache prune --ci